version: '2'
services:
  wlp:
    image: 'websphere-liberty:beta'
    hostname: 'websphere9'
    ports:
      - '9080:9080'
      - '9443:9443'
      - '7777:7777'
    environment:
    - JVM_ARGS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7777'